[Node1]
server = 127.0.0.1:10009
macpath = /code/data/credentials/readonly.macaroon
tlspath = /code/data/credentials/tls.cert

# Enable and set pubkey if listener node is private and non-routing
hide_listener_node = 0

# Enable if listener node is missing channel data after running on neutrino
use_include_unannounced_workaround = 0

# Must be set if using hide_listener_node or use_include_unannounced_workaround
listener_node_pub = pubkey

# Enable to always refresh the graph on startup, even if not yet stale.
refreshgraphonstart = 0

# Enable to establish gossip connections to random nodes for better network knowledge.
# Requires additional permissions, will not work with readonly macaroon.
randomgossipconnections = 0
